export const demoProfiles = [
  { name: "Hot junk removal", input:{business_name:'Quick Haul',contact_name:'Alex',phone:'111',industry:'junk removal',service_area:'Dallas',lead_sources:["Phone calls","Website form","Instagram/Facebook DMs"],pain_points:["Missed calls","Slow replies"],urgency_answer:"Happens often and hurts",average_job_value_answer:"$250–$500",current_tools:["Gmail"],fit_check_answer:"I want leads answered and tracked"}, expected:{recommended_system:"Missed Lead Fix",confidence:['High'],deposit_allowed:true,next_best_action:'Send Recommendation'}},
  { name:"Lawn care quotes", input:{business_name:'GreenCut',contact_name:'Sam',email:'a@b.com',industry:'lawn care',service_area:'Austin',lead_sources:["Phone calls","Website form"],pain_points:["Quotes get lost","We forget to follow up"],urgency_answer:"Could cost us a job",average_job_value_answer:"$250–$500",current_tools:["Google Sheets","Gmail"],fit_check_answer:"I want quotes followed up"}, expected:{recommended_system:"Quote Follow-Up Fix",deposit_allowed:true}},
  { name:"Cleaning reviews", input:{business_name:'Sparkle',contact_name:'Kim',phone:'222',industry:'cleaning',service_area:'Miami',lead_sources:["Email","Phone calls"],pain_points:["Reviews do not get requested","Old customers are not re-contacted"],urgency_answer:"Annoying",average_job_value_answer:"$100–$250",current_tools:["Gmail"],fit_check_answer:"I want reviews and old customers handled"}, expected:{recommended_system:"Review + Reactivation Fix"}},
  { name:"Med spa sensitive intake", input:{business_name:'Skin',contact_name:'Dr Z',phone:'333',industry:'med spa',service_area:'LA',lead_sources:["Phone calls"],pain_points:["I do too much manually"],urgency_answer:"Could cost us a job",average_job_value_answer:"$500+",current_tools:["Not sure"],fit_check_answer:"I need help with legal/medical/financial intake"}, expected:{recommended_system:"Manual Review / Not Fit Yet",deposit_allowed:false}},
  { name:"Custom software request", input:{business_name:'BuildCo',contact_name:'Lee',phone:'444',industry:'moving',service_area:'NYC',lead_sources:["Phone calls"],pain_points:["Missed calls"],urgency_answer:"Could cost us a job",average_job_value_answer:"$500+",current_tools:["Gmail"],fit_check_answer:"I want custom software"}, expected:{recommended_system:"Manual Review / Not Fit Yet",deposit_allowed:false}},
  { name:"Low-value low-urgency", input:{business_name:'CheapFix',contact_name:'Jo',phone:'999',industry:'handyman',service_area:'Tulsa',lead_sources:["Phone calls"],pain_points:["I do too much manually"],urgency_answer:"Not a big deal",average_job_value_answer:"Under $100",current_tools:["Mostly phone/text"],fit_check_answer:"I am not sure"}, expected:{deposit_allowed:false}},
  { name:"Missing phone/email", input:{business_name:'NoContact',contact_name:'Pat',industry:'cleaning',service_area:'Austin',lead_sources:["Email"],pain_points:["Slow replies"],urgency_answer:"Could cost us a job",average_job_value_answer:"$250–$500",current_tools:["Gmail"],fit_check_answer:"I want leads answered and tracked"}, expected:{deposit_allowed:false, next_best_action:'Request Missing Info'}},
  { name:"Multiple pain points", input:{business_name:'MultiPain',contact_name:'Ray',phone:'888',industry:'junk removal',service_area:'Phoenix',lead_sources:["Phone calls","Website form","Instagram/Facebook DMs"],pain_points:["Missed calls","Quotes get lost","Reviews do not get requested"],urgency_answer:"Could cost us a job",average_job_value_answer:"$500+",current_tools:["Gmail"],fit_check_answer:"I want leads answered and tracked"}, expected:{recommended_system:"Missed Lead Fix"}}
];
